In [1]:
import pandas as pd
import os
import warnings

In [2]:
#When exporting, include the other information

file_path = os.path.join(os.path.expanduser('~'), 'OneDrive - 2X LLC', 'Desktop', '!Python Scripts', 'Testing', 'PCS DWC', 'hubspot-crm-exports-investment-advisor-contact-tier-2026-04-06.xlsx')
#file_path = os.path.join(os.path.expanduser('~'), 'OneDrive - 2X LLC', 'Desktop', 'All Covered', 'AC-lifecycle-stage.xlsx')

df = pd.read_excel(file_path)
warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")

C:\Users\SiakFoongYap\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [3]:
df

,Record ID,Email,Investment Advisor Contact Tier Current Value,Change Date (America/Detroit),Change Source,Changed By,Previous Value (1),Change Date (1) (America/Detroit),Change Source (1),Changed By (1),Previous Value (2),Change Date (2) (America/Detroit),Change Source (2),Changed By (2),...,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,51706751,kim@cowdellagency.com,Tier 3,2021-02-23 18:24:00,Workflow,Contact Tier Assignment - Tier 3,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN
1,41069304,mary.chiodo@rsmus.com,Tier 3,2020-05-27 13:14:00,Workflow,Contact Tier Assignment - Tier 3,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN
2,97507421242,audrey.stansbury@edwardjones.com,Tier 3,2025-02-06 17:07:00,Workflow,Contact Tier Assignment - Tier 3,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN
3,51437921,juan_estarellas@ml.com,Tier 3,2021-02-18 15:25:00,Workflow,Contact Tier Assignment - Tier 3,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN
4,2163435,debbie@ffgplanning.com,Tier 3,2019-08-30 14:28:00,Workflow,Contact Tier Assignment - Tier 3,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17219,18673,jeff@arsadvisor.com,Tier 3,2019-08-30 14:28:00,Workflow,Contact Tier Assignment - Tier 3,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN
17220,19740604,josh@dpwbenefits.com,Tier 3,2019-08-30 14:28:00,Workflow,Contact Tier Assignment - Tier 3,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN
17221,19176,susie.sanders@edwardjones.com,Tier 2,2020-11-25 14:30:00,Workflow,Contact Tier Assignment - Tier 2,Tier 3,2019-08-30 14:28:00,Workflow,Contact Tier Assignment - Tier 3,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN
17222,40865413,bob@criswellwyatt.com,Tier 3,2020-05-20 11:58:00,Workflow,Contact Tier Assignment - Tier 3,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN
17223,41069451,bryan.person@wellsfargoadvisors.com,Tier 3,2020-05-27 13:14:00,Workflow,Contact Tier Assignment - Tier 3,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN

In [4]:
# Identify the first two columns as identifiers
identifier_columns = ['Record ID', 'Email']

# Initialize an empty list to store the stacked DataFrames
stacked_df_list = []

# Iterate through the columns in pairs, starting from the third column
num_columns = len(df.columns)
for i in range(2, num_columns, 4):
    # Select the current pair of columns along with the identifier columns
    pair_df = df[identifier_columns + [df.columns[i], df.columns[i + 1], df.columns[i + 2], df.columns[i + 3]]]

    # Drop rows where the second column in the pair has NaN
    pair_df = pair_df.dropna(subset=[df.columns[i + 1]])

    # Rename the columns to have consistent names
    pair_df.columns = identifier_columns + ['Value', 'Change Date (US/Eastern)', 'Change Source', 'Changed By']
    
    # Append the pair_df to the list
    stacked_df_list.append(pair_df)

# Concatenate all the DataFrames in the list
final_df = pd.concat(stacked_df_list, ignore_index=True)

# Output the result
final_df

,Record ID,Email,Value,Change Date (US/Eastern),Change Source,Changed By
0,51706751,kim@cowdellagency.com,Tier 3,2021-02-23 18:24:00,Workflow,Contact Tier Assignment - Tier 3
1,41069304,mary.chiodo@rsmus.com,Tier 3,2020-05-27 13:14:00,Workflow,Contact Tier Assignment - Tier 3
2,97507421242,audrey.stansbury@edwardjones.com,Tier 3,2025-02-06 17:07:00,Workflow,Contact Tier Assignment - Tier 3
3,51437921,juan_estarellas@ml.com,Tier 3,2021-02-18 15:25:00,Workflow,Contact Tier Assignment - Tier 3
4,2163435,debbie@ffgplanning.com,Tier 3,2019-08-30 14:28:00,Workflow,Contact Tier Assignment - Tier 3
...,...,...,...,...,...,...
19739,45743601,cpayne056@gmail.com,Tier 3,2020-10-06 10:56:00,Workflow,Contact Tier Assignment - Tier 3
19740,6503501,david@schneiderconsultants.com,Tier 2,2019-08-30 14:25:00,Workflow,Contact Tier Assignment - Tier 2
19741,32360501,wcmassey@levelfouradvisors.com,Tier 3,2019-10-23 12:21:00,Workflow,Contact Tier Assignment - Tier 3
19742,32915551,alex_eaton@troweprice.com,Tier 1,2019-11-07 11:42:00,CRM UI,Doug Hoefer
19743,33115501,david_crotty@troweprice.com,Tier 1,2019-11-15 12:31:00,CRM UI,Doug Hoefer

In [4]:
# Identify the first two columns as identifiers
identifier_columns = ['Record ID', 'Email']

# Initialize an empty list to store the stacked DataFrames
stacked_df_list = []

# Iterate through the columns in pairs, starting from the third column
num_columns = len(df.columns)
for i in range(2, num_columns, 4):
    # Check if there are enough columns left to form a complete quartet
    if i + 3 >= num_columns:
        break  # Exit the loop if there are not enough columns left

    # Select the current quartet of columns along with the identifier columns
    quartet_df = df[identifier_columns + [df.columns[i], df.columns[i + 1], df.columns[i + 2], df.columns[i + 3]]]
    
    # Drop rows where the fourth column in the quartet has NaT
    quartet_df = quartet_df.dropna(subset=[df.columns[i + 3]])

    # Rename the columns to have consistent names
    quartet_df.columns = identifier_columns + ['Campaign UTM Current Value', 'Campaign UTM Change Date (US/Eastern)', 'Campaign UTM Change Source', 'Campaign UTM Changed By']
    
    # Append the pair_df to the list
    stacked_df_list.append(quartet_df)

# Concatenate all the DataFrames in the list
final_df = pd.concat(stacked_df_list, ignore_index=True)

# Output the result
final_df

,Record ID,Email,Campaign UTM Current Value,Campaign UTM Change Date (US/Eastern),Campaign UTM Change Source,Campaign UTM Changed By
0,51706751,kim@cowdellagency.com,Tier 3,2021-02-23 18:24:00,Workflow,Contact Tier Assignment - Tier 3
1,41069304,mary.chiodo@rsmus.com,Tier 3,2020-05-27 13:14:00,Workflow,Contact Tier Assignment - Tier 3
2,97507421242,audrey.stansbury@edwardjones.com,Tier 3,2025-02-06 17:07:00,Workflow,Contact Tier Assignment - Tier 3
3,51437921,juan_estarellas@ml.com,Tier 3,2021-02-18 15:25:00,Workflow,Contact Tier Assignment - Tier 3
4,2163435,debbie@ffgplanning.com,Tier 3,2019-08-30 14:28:00,Workflow,Contact Tier Assignment - Tier 3
...,...,...,...,...,...,...
19537,45743601,cpayne056@gmail.com,Tier 3,2020-10-06 10:56:00,Workflow,Contact Tier Assignment - Tier 3
19538,6503501,david@schneiderconsultants.com,Tier 2,2019-08-30 14:25:00,Workflow,Contact Tier Assignment - Tier 2
19539,32360501,wcmassey@levelfouradvisors.com,Tier 3,2019-10-23 12:21:00,Workflow,Contact Tier Assignment - Tier 3
19540,32915551,alex_eaton@troweprice.com,Tier 1,2019-11-07 11:42:00,CRM UI,Doug Hoefer
19541,33115501,david_crotty@troweprice.com,Tier 1,2019-11-15 12:31:00,CRM UI,Doug Hoefer

In [5]:
final_df.to_excel('PCS Tier Test.xlsx', index=False)

In [6]:
filtered_df = df[df['Email'] == "siakfoong.yap@2x.marketing"]
pd.set_option('display.max_columns', None)
filtered_df

Empty DataFrame
Columns: [Record ID, Email, Investment Advisor Contact Tier Current Value, Change Date (America/Detroit), Change Source, Changed By, Previous Value (1), Change Date (1) (America/Detroit), Change Source (1), Changed By (1), Previous Value (2), Change Date (2) (America/Detroit), Change Source (2), Changed By (2), ..., Unnamed: 15, Unnamed: 16, Unnamed: 17]
Index: []

In [9]:
pd.reset_option('display.max_columns')